apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCKYWz/kwsBWFJ9+8vnOs6XNzO55+AVU/nQrQVjoIzovs01MNOK2HfNKNCgwJJOsjitFIGe8LEuMZMgoW/pxlUkXh+y1dSv0MQ8fYhnE2KSQ0DHHNljILTNMey2Xjl8zG0gqHTgQL4dYLyk3+bNCL8418waxM8N/pIkWPqC+ZpjTWcwTqoQILfiKVeLucDnwdVsBEnjhzoFIz/4B5j7OHTxE0srD7vlCfHKbFJBJDl8gLgGOscATs5iKd2JaOmgjEPtOC2A9wG8HAoBdoTFOrOE0dKYRdvDHN6nIMtQOywlhA5ocKS8Csmgq3KtximZUF4VshQ8PjU31eC4QgCPCQ4BMw3IUcUnhnMtbHsnrt6h08Bk39eivNHPiyBI02KeaI7Z0Bj+4WXQNJGpJQSffZnx17aXpH5R1FD6vJTYirlepbaRj97F5dl+Q4pyryZYjdO76uaDooNcwBVAtCCPnwtR4bmLUOnzoZz8NBCQ2jfUMKLw1jDs0B16mz3XhVGWZd5uRuKdCFJbDAP/XaVx3Y/auK5pKHHP44OikCvbCAj/CFN6C2bOc7nSimea7Yjcoo/FJ48jIut1I+g071PkCs4sPozpnHbmzikOJTnydgQpdnUo8hV/WngnUqgos3nUOeSrHpdu8Zggcjyc2Ai8Zn32veYW78Yze1xkqD43gGnrnD8OsKYA0a6sNoX3kjxDsyNi6krAvXiuTw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-nonprod
    type: Opaque

