apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-nonprod
spec:
  encryptedData:
    DB_PASSWORD: AgBGrTsy7dpYtrva+tLrI59zjP1Ptbl2pVLc8LB0ex4BxVWSwWMTM1xhYC+boCJKwJoYawh3X66ASNATfBh2QTneuw7/Kx/vqtv1womB1UzCMpj7mpdIoTVLxomCaoWELNOwG4HfED+AvF1JubqNt2+PhY8HvrGL6n65b1WHDbE3DPCF3vaJl0Iu2o4K6EYYLfQHtUY/pCMQB529KrMbesRaG2OX94aCvrFoNxkl8PzbebEmbIBWmCsfuEzVj4VvSpzX7S2beRM5sOoroE4y4HGALH4TLiItYXR72CNIVwCGh275qTU0bX69Ajzo6+30sc3LGgreuO3sGbGsVdfh+Q1cHLKsPOMku0PrIgS3YAVEl2ydkOsc4ZMVtp2tffAabiBJu6ESAGF/17bgVrxiTi4/1Ug3gDiPBrzc46e1wIfSoITaPJqBEyuzYcFCZuIPD6zjF6LLCsb6DjtMXY85p+XQBCwirAKjZ85cIaP5GzBce+EHtNHAuZAf3NPBIQI+vNhuApOhLG13rY8XLBawXR9DHY39B/zOy+95ZpKBkdmxYBHWLNaeUvtQPyWH4/AFwY+TSHf0FbS9y3unGJNAR2RTLmZ956rbo70vHr4WCE83zHi1w2N+9tim3mr8DjFLbz0CYINyP663xrHvp9mXNi0htTsqIhSgTVEsD3hrmaHq4jjB/OWFLoE7eFHtrjVoYhMKX8s8uR7M9Q==
    DB_USER: AgA9GmF1ZR0OD4FqHf+ChMLF7EVNlPf0ddvPe5UofFSkBBxe0P6QF9IGekgNgJcuS2MDs6VX6ZPT8xA1j/rGJs3MY2ZWaUu00GLyvQgQyGUOMvfLwkXN/W4K/my8JpNU2CAeIEDmEjrIJcIrMQqlukJP9SHSAmt+eUd81g/sYds0foCxs8GJm6EduuCPaLiExU/b8NmW8ErFqXB24oNjwAiucCfMrGPIBrqDEg6ffaKbj1NpYU+aVHZ9E3QErgusVOhnChHRdBartXUlVDNp+QZ1PEAJhxnA2wtZylMM3Vpy35qKjFEzOxwL8w+QHWFqIwJEF8+pvi3CY7Th6qcLWMKJWWviGhkZvtcjEVtKkjocDT6VJQMZ83sMVqnitUmF5JbqmzZHcZ+AvBFwcblRuOa+QgQkdrMRd6f0C9WS0ZBprr3F+nuEbWn9/q8YxnW7Au4bxpCOiTkx/G/EYIZj2Xkwk3GPx1rqu9zqEyO8GDa6AkwtsJan7fvDm43yA1N07PdzczFl0/nA8AuHEmmjQarYco2ezj8FiAP4vCEJef19y2MiUuaEJ//8gM8Jm12nOHei+DZFaJHgAMud4FOJVvv32oxHJpO+iVv9iFimrlwWETa/k0cmuZVjtWScc5rpQl4lf7MNK9eHDm9ZrcZrT3B1BhmOir5zSc+wBb++DKWTiSDkHNKwqrp7RkbPwkIdw9TXanN31IQAgQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-nonprod
    type: Opaque

